### ISSUE TITLE
FYI installation instructions

### ISSUE THREAD

**Issue by quiveringlemon** [theyoucheng/cbmc#6]
Just leaving the installation instructions here (no issue)...

git clone https://github.com/theyoucheng/cbmc cbmc && cd cbmc && git checkout fault-localization-incr && cd src && make minisat2-download && make

cd cbmc && cd src && git pull origin fault-localization-incr && make

**Comment by quiveringlemon** [comment]
EXAMPLE - commands & example minmax.c

cbmc minmax.c --incremental --stop-on-fail --unwind 1 --localize-faults --localize-faults-max-traces 20 --localize-faults-method pfl --localize-faults-max-display 10 --verbosity 0 --slice-formula --beautify

int BLOCK=0;
int main () {
  int inp1, inp2, inp3; int least = inp1;
  int most = inp1;

  int x;
  if (x == 0) 
    x += 1; // irrelevant - should be sliced out!

  if (most < inp2)
    most = inp2; // C1

  if (most < inp3) 
    most = inp3; // C2

  if (least > inp2)
    most = inp2; // C3 (fault#1)

  if (least > inp3) 
    least = inp3; // C4


  assert(least<=most); //

}

**Comment by theyoucheng** [comment]
To run the "single bug optimal" fault localization framework (e.g., on `file.c`)
`````
cbmc file.c --incremental --stop-on-fail --unwind-min 1 --unwind-max 1 --localize-faults --localize-faults-method sbo --localize-faults-max-display 10 --verbosity 0 --slice-formula --beautify
``````
The implementation of "fault localization" is based on the "incremental CBMC", and the configuration with `--unwind-min 1 --unwind-max 1` outperforms simply using `--unwind 1`

**Comment by quiveringlemon** [comment]
make minisat2-download && make doesn't seem to work - any suggestions? Here is the error message - seems to be something wrong with "goto-diff" and i'm not sure whether it's the cbmc end of things or whether i need to install something new?

make[1]: Entering directory '/home/dlandsbe/Programs/CBMC/cbmc/src/goto-diff'
make[1]: Warning: File '../common' has modification time 171979 s in the future
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o goto_diff_main.o goto_diff_main.cpp
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o goto_diff_parse_options.o goto_diff_parse_options.cpp
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o goto_diff_languages.o goto_diff_languages.cpp
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o goto_diff_base.o goto_diff_base.cpp
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o syntactic_diff.o syntactic_diff.cpp
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o unified_diff.o unified_diff.cpp
g++ -c -MMD -MP -std=c++11 -Wall -O2 -I .. -DHAVE_JAVA_BYTECODE -o change_impact.o change_impact.cpp
g++  -o goto-diff -Wl,--start-group ../ansi-c/ansi-c.a ../cpp/cpp.a ../linking/linking.a ../big-int/big-int.a ../goto-programs/goto-programs.a ../assembler/assembler.a ../pointer-analysis/pointer-analysis.a ../analyses/analyses.a ../langapi/langapi.a ../xmllang/xmllang.a ../util/util.a ../solvers/solvers.a goto_diff_main.o goto_diff_parse_options.o goto_diff_languages.o goto_diff_base.o syntactic_diff.o unified_diff.o change_impact.o ../java_bytecode/java_bytecode.a -Wl,--end-group 
../pointer-analysis/pointer-analysis.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:50: recipe for target 'goto-diff' failed
make[1]: *** [goto-diff] Error 1
make[1]: Leaving directory '/home/dlandsbe/Programs/CBMC/cbmc/src/goto-diff'
Makefile:49: recipe for target 'goto-diff.dir' failed
make: *** [goto-diff.dir] Error 2

**Comment by theyoucheng** [comment]
I just tried the following command (the one you left above) and it compiled FCBMC successfully on my laptop...

git clone https://github.com/theyoucheng/cbmc cbmc && cd cbmc && git checkout fault-localization-incr && cd src && make minisat2-download && make

**Comment by theyoucheng** [comment]
Here is a list of required software for the compilation of CBMC/FCBMC https://github.com/theyoucheng/cbmc/blob/master/COMPILING

**Comment by quiveringlemon** [comment]
Excellent that all works thanks! (I had missed a couple of packages so the required software list was v helpful) ... Hopefully all these comments will be useful to people who download the tool :)
